config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords' }

  root to: 'welcomes#index'

  namespace :backend do
    resources :users
    resources :song_poems
    resources :tang_poems
    resources :qin_poetries
    resources :han_poetries
    resources :articles
  end

  namespace :profile do
    resource :basic
  end

  resources :qin_poetries, :song_poems, :tang_poems, :han_poetries, :articles, :dongps, :jiaxs do
    collection do
      get :poetries
      get :yuefus
      get :cis
      get :essays
    end
  end

  resources :welcomes, only: [ :index ]
  resources :works, only: [] do
    resources :suggestions
    resource :flip
  end

  get 'about', to: 'main#about'
  get 'search', to: 'main#search'
  delete "/users/sign_out" => "users/sessions#destroy"
end

app/views/shared/_flip.html.erb
<% @work = work %>
<div class="d-flex justify-content-end my-2 mx-3">
  <% if current_user&.flipped(work) %>
    <%= render file: "flips/show.xhrml" %>
  <% else %>
    <%= render file: "flips/new.xhrml" %>
  <% end %>
</div>

app/views/shared/_list.html.erb
<% essays = works.where(category: :essay) %>
<% poems = works.where(category: [ :poetry, :song ]) %>
<% yuefus = works.where(category: :yuefu) %>
<% cis = works.where(category: :ci) %>

<% if essays.present? %>
  <h2 class="category">文集</h2>
  <%= render "shared/backend/fliped", likes: essays %>
<% end %>

<% if poems.present? %>
  <h2 class="category">诗歌</h2>
  <%= render "shared/backend/fliped", likes: poems %>
<% end %>

<% if yuefus.present? %>
  <h2 class="category">乐府</h2>
  <%= render "shared/backend/fliped", likes: yuefus %>
<% end %>

<% if cis.present? %>
  <h2 class="category">词集</h2>
  <%= render "shared/backend/fliped", likes: cis %>
<% end %>

app/views/shared/_poem_detail.html.erb
<div class="container">
  <div class="row my-5">
    <div class="col-md-10 col-10 col-lg-10 col-sm-10 offset-md-1">
      <div class="d-flex flex-column align-items-center">
        <div class="d-flex align-items-end">
          <h1 class="text-success"><%= work.title %></h1>
          <div id="work-flip-<%= work.id %>">
            <%= render 'shared/flip', work: work %>
          </div>
        </div>
        <br>
        <div class="text-muted"><%= work.dynasty %> - <%= work.author %></div>
        <br>
        <% if work.prelude.present? %>
          <div class="mx-5 text-muted"><%= work.prelude %></div>
          <br>
        <% end %>
        <div class="font-weight-normal">
        <% work.content.each do |line| %>
          <p class="poem-body"><%= line %></p>
        <% end %>
        </div>
      </div>
    </div>
  </div>

  <hr>
  <h2 class="category"><%= h Work, :notes %></h2>
  <div class="mx-5">
    <% if work.notes.empty? %>
      <h5 class="font-weight-normal">暂无 <%= link_to '我来补充', [ :edit, :backend, work ] if can? :update, work %></h5>
    <% else %>
      <% work.notes.each do |line| %>
        <p><%= line %></p>
      <% end %>
    <% end %>
  </div>

  <h2 class="category"><%= h Work, :translate %></h2>
  <div class="mx-5">
    <% if work.translate.empty? %>
      <h5 class="font-weight-normal">暂无 <%= link_to '我来补充', [ :edit, :backend, work ] if can? :update, work %></h5>
    <% else %>
      <% work.translate.each do |line| %>
        <p><%= line %></p>
      <% end %>
    <% end %>
  </div>

  <% if work.translate_res.present? %>
    <h2 class="category"><%= h Work, :translate_res %></h2>
    <div class="mx-5">
      <% work.translate_res.each do |line| %>
        <div class="small text-muted"><%= line %></div>
      <% end %>
    </div>
  <% end %>

  <h2 class="category">我要完善</h2>
  <div class="mx-5">
    <div class="row">
      <div class="col-md-12">
        <% url = local_assigns[:trick] ? work_suggestions_path(work, trick: trick) : work_suggestions_path(work) %>
        <%= simple_form_for(suggestion, as: :suggestion, url: url, method: :post) do |f| %>
          <%= f.input :email, as: :email %>
          <%= f.input :comments, as: :text, label: false, placeholder: "#{work.title}......" %>
          <%= f.submit '提交', class: "btn btn-success float-right" %>
        <% end %>
      </div>
    </div>
  </div>
</div>