config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords' }

  root to: 'welcomes#index'

  namespace :backend do
    resources :users
    resources :song_poems
    resources :tang_poems
    resources :qin_poetries
    resources :han_poetries
    resources :articles
  end

  namespace :profile do
    resource :basic
  end

  resources :qin_poetries, :song_poems, :tang_poems, :han_poetries, :articles, :dongps, :jiaxs do
    collection do
      get :poetries
      get :yuefus
      get :cis
      get :essays
    end
  end

  resources :welcomes, only: [ :index ]
  resources :works, only: [] do
    resources :suggestions
    resource :flip
  end

  get 'about', to: 'main#about'
  get 'search', to: 'main#search'
  delete "/users/sign_out" => "users/sessions#destroy"
end

app/models/flip.rb
# == Schema Information
#
# Table name: flips
#
#  id         :integer          not null, primary key
#  work_id    :integer
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Flip < ApplicationRecord
  belongs_to :user
  belongs_to :work
end

app/controllers/flips_controller.rb
class FlipsController < ApplicationController
  before_action :authenticate_user!

  load_and_authorize_resource :work
  before_action -> { @user = current_user }

  def new
  end

  def create
    flash.keep(:alert)
    @flip = @work.flips.new
    @flip.user = @user
    @flip.save
    respond_with @flip
  end

  def show
  end

  def destroy
    @flip = @work.flips.where(user_id: @user).take
    @flip.destroy
    respond_with @flip
  end
end

app/views/flips/create.xhrml.erb
<%= render file: "flips/show.xhrml" %>

app/views/flips/destroy.xhrml.erb
<%= render file: "flips/new.xhrml" %>

app/views/flips/new.xhrml.erb
<% data = { remote: true, type: "xhrml", target: "div" } %>
<%= link_to work_flip_url(@work), method: :post, class: 'd-flex align-items-center', data: data do %>
  <i class="far fa-grin-hearts fa-lg text-muted"></i>
  <span class="badge badge-pill badge-success ml-2"><%= @work.flips.count %></span>
<% end %>

app/views/flips/show.xhrml.erb
<% data = { remote: true, type: "xhrml", target: "div" } %>
<%= link_to work_flip_url(@work), method: :delete, class: 'd-flex align-items-center', data: data do %>
  <i class="fas fa-grin-hearts fa-lg text-danger"></i>
  <span class="badge badge-pill badge-success ml-1"><%= @work.flips.count %></span>
<% end %>